### ISSUE TITLE
BedrockConnect needs an update

### ISSUE THREAD

**Issue by ghost** [LazyBirb/LazyBirb#1]
I'm new on here so I don't know of this is correct place to tell you

But, is it ok if you update your server to the latest Minecraft Version 1.21 (Tricky Trails) because I wasn't able to use it cause I got a Minecraft message saying this is not updated.

Hope this get fixed.
Thank You for reading.

**Comment by LazyBirb** [comment]
Hey thanks for letting me know, the update usually takes a couple of minutes so ill update the server now!

**Comment by LazyBirb** [comment]
Instance got updated, thanks again for telling!
