### ISSUE TITLE
The server is not appearing in my friends list 

### ISSUE THREAD

**Issue by joldfield101** [LazyBirb/LazyBirb#3]
I have been using this on my switch for weeks now and it’s been great - thank you! But now my friends list is empty and your server is not there. Is this to do with the new version release?

**Comment by LazyBirb** [comment]
Thanks for informing me, it seemed like the xboxbroadcaster hung itself up, I restarted it again and it should work now again

**Comment by LazyBirb** [comment]
Please inform me if it works again as I'm unable to test it out for myself

**Comment by joldfield101** [comment]
And we’re back!

Thank you very much 👍🏼👍🏼👍🏼👍🏼

Jez


<http://www.justgiving.com/joldfield101>
