### ISSUE TITLE
Not visible in friends list

### ISSUE THREAD

**Issue by joldfield101** [LazyBirb/LazyBirb#4]
Hi - your server has disappeared from my friends list again. It appears to be every time there is an update??

**Comment by LazyBirb** [comment]
Seems like there's a internal server problem with the temp storage, I'm working on to get the instance up as soon as possible!

**Comment by LazyBirb** [comment]
Problem found, it's due to a faulty config in the MCXboxBroadcast, expect a fix soon

**Comment by LazyBirb** [comment]
Should be up and running again, expect the scheduled restarts, I won't be able to test or monitor this for today

**Comment by joldfield101** [comment]
No worries 🫡

Thanks for sorting it out! 👍🏼

Jez

**Comment by joldfield101** [comment]
It’s back up! Excellent … thank you

Jez
