### ISSUE TITLE
MCXboxBroadcast not working after 1.21.20 update

### ISSUE THREAD

**Issue by joldfield101** [LazyBirb/LazyBirb#5]
Even though you show up on my friends list, when I try connect it fails. I have tried 4 networks, rebooted, reinstalled… is it related to the realms being down atm?

**Comment by LazyBirb** [comment]
Im sorry for the inconvenience, unfortunately I'm unable to do anything due to a update bugging out the broadcaster, currently there is no fix for it, but as soon as there is the broadcaster will be back available.
More info: https://github.com/rtm516/MCXboxBroadcast/issues/122
