### ISSUE TITLE
Can't connect to world 

### ISSUE THREAD

**Issue by DominikP78** [LazyBirb/LazyBirb#6]
Hi! I hope it's okay that I contact you this way. I've got a problem with your BedrockConnect server. I've used it for a few months now on Nintendo Switch. I've been on holiday for 2 weeks and now it doesn't work anymore. It always tries to connect to the server for some time and then says that it couldn't connect to the server. I've also tried the DNS method but that just connected me to the default server normally. Also other BedrockConnect servers also don't work for me. I probably did something wrong. Can you help me please?

**Comment by LazyBirb** [comment]
Hmm thats strange, I haven't seen any odd behaviour on the instance so far

**Comment by DominikP78** [comment]
Thanks for replying! I just checked again if it works now and it works with the DNS method. I didn't change any settings since yesterday, it just started working now.

**Comment by LazyBirb** [comment]
This seems odd, i assume there was a client sided error or the server wasnt responding at the time, please mind that there are scheduled downtimes!
